        parsing_table = {
            'MAIN': {'$': ['ε'],
                    ';': ['STMT'],
                    'def': ['FLIST'],
                    'id': ['STMT'],
                    'if': ['STMT'],
                    'int': ['STMT'],
                    'print': ['STMT'],
                    'return': ['STMT'],
                    '{': ['STMT']},
            'STMT': {';': [';'],
                    'id': ['print', ';'],
                    'if': ['IFSTMT'],
                    'int': ['int', 'id', ';'],
                    'print': ['PRINTST', ';'],
                    'return': ['RETURNST', ';'],
                    '{': ['{', 'STMTLIST', '}']},
            'FLIST': {'def': ['FDEF', "FLIST'"]},
            'FDEF': {'def': ['def', 'id', '(', 'PARLIST', ')', '{', 'STMTLIST', '}']},
            "FLIST'": {'$': ['ε'], 'def': ['FLIST']},
            'PARLIST': {')': ['ε'], 'int': ['int', 'id', "PARLIST'"]},
            'STMTLIST': {';': ['STMT', "STMTLIST'"],
                    'id': ['STMT', "STMTLIST'"],
                    'if': ['STMT', "STMTLIST'"],
                    'int': ['STMT', "STMTLIST'"],
                    'print': ['STMT', "STMTLIST'"],
                    'return': ['STMT', "STMTLIST'"],
                    '{': ['STMT', "STMTLIST'"]},
            "PARLIST'": {')': ['ε'], ',': [',', 'PARLIST']},
            'ATRIBST': {'id': ['id', '=', "ATRIBST'"]},
            'PRINTST': {'print': ['print', 'EXPR']},
            'RETURNST': {'return': ['return']},
            'IFSTMT': {'if': ['if', '(', 'EXPR', ')', 'STMT', "IFSTMT'"]},
            "ATRIBST'": {'(': ['EXPR'],
                    'call': ['FCALL'],
                    'id': ['EXPR'],
                    'num': ['EXPR']},
            'EXPR': {'(': ['NUMEXPR', 'COMP_EXPR'],
                    'id': ['NUMEXPR', 'COMP_EXPR'],
                    'num': ['NUMEXPR', 'COMP_EXPR']},
            'FCALL': {'call': ['call', 'id', '(', 'PARLISTCALL', ')']},
            'PARLISTCALL': {'id': ['id', "PARLISTCALL'"]},
            "PARLISTCALL'": {')': ['ε'], ',': [',', 'PARLISTCALL']},
            "IFSTMT'": {'$': ['ε'],
                    'else': ['ELSE DANGLING'],    
                    'id': ['ε'],
                    'if': ['ε'],
                    'int': ['ε'],
                    'print': ['ε'],
                    'return': ['ε'],
                    '{': ['ε'],
                    '}': ['ε']},
            "STMTLIST'": {';': ['STMTLIST'],
                    'id': ['STMTLIST'],
                    'if': ['STMTLIST'],
                    'int': ['STMTLIST'],
                    'print': ['STMTLIST'],
                    '{': ['STMTLIST'],
                    '}': ['ε']},
            'NUMEXPR': {'(': ['TERM', "NUMEXPR'"],
                    'id': ['TERM', "NUMEXPR'"],
                    'num': ['TERM', "NUMEXPR'"]},
            'COMP_EXPR': {')': ['ε'],
                    ';': ['ε'],
                    '<': ['<', 'NUMEXPR'],
                    '==': ['==', 'NUMEXPR'],
                    '>': ['>', 'NUMEXPR']},
            'TERM': {'(': ['TERM', "NUMEXPR'"],
                    'id': ['TERM', "NUMEXPR'"],
                    'num': ['TERM', "NUMEXPR'"]},
            "NUMEXPR'": {')': ['ε'],
                    '+': ['+', 'TERM', "NUMEXPR'"],
                    '-': ['-', 'TERM', "NUMEXPR'"],
                    ';': ['ε'],
                    '<': ['ε'],
                    '==': ['ε'],
                    '>': ['ε']},
            'FACTOR': {'(': ['(', 'NUMEXPR', ')'], 'id': ['id'], 'num': ['num']}, 
            "TERM'": {'*': ['*', 'FACTOR', "TERM'"],
                    '+': ['ε'],
                    '-': ['ε'],
                    ';': ['ε'],
                    '<': ['ε'],
                    '==': ['ε'],
                    '>': ['ε'],
                    '{': ['ε']}
        }
